### ISSUE TITLE
Go Modules support

### ISSUE THREAD

**Issue by kyoungho** [rticommunity/rticonnextdds-connector-go#13]
### Proposal:
Go 1.11 and 1.12 include preliminary support for Go Modules. From Go 1.13, Go Modules will be the default. It would be nice to have a CI for Go Modules and add instruction in the getting started section. 

https://blog.golang.org/using-go-modules

### Current behavior:
No CI
No getting started instruction for Go Modules

### Desired behavior:
Having CI for Go Modules
Having getting started Instruction for Go modules

### Use case:
It will be useful for users using go mod for dependency management

**Comment by metarsit-nutonomy** [comment]
@kyoungho this can be closed
