### ISSUE TITLE
Tagging version

### ISSUE THREAD

**Issue by metarsit** [rticommunity/rticonnextdds-connector-go#17]
### Proposal:
At some point can we tag the master commit? e.g. v0.0.1

### Use case:
This will make go mod on other people's repo a lot cleaner and nicer.

**Comment by metarsit** [comment]
@kyoungho

**Comment by kyoungho** [comment]
@metarsit Created the v0.1 tag to the latest commit (39d4c37747e39b8c5776affe1c3e1b072052aa32).

**Comment by metarsit** [comment]
Perfect! Thanks!
