### ISSUE TITLE
Removing Git LFS

### ISSUE THREAD

**Issue by metarsit** [rticommunity/rticonnextdds-connector-go#20]
### Proposal:
- Remove Git LFS

### Use case:
- With Git LFS, we have a lot of challenges trying to get RTI repo nicely compatible with the GO 1.13. I speculate that it is due to Git LFS after close result in different checksum as before it was downloaded. I think we should do something about it to make it better till GO fully support Git LFS.

**Comment by metarsit** [comment]
@kyoungho Please advice on this :)

**Comment by kyoungho** [comment]
@metarsit I could not find other options than Git LFS to store large binary files. Do you have any suggestions? What is the error message you see?

**Comment by metarsit** [comment]
Basically for `go get` to work properly, you will need Git LFS for the libraries files.. 
That suck in a way, 😆 so I was hoping if we can do something about It, that would be great

**Comment by kyoungho** [comment]
Right. Git LFS is required to clone the repository properly. While I explored a way for providing large C library files, Git LFS was the best option. Please let me know if you can find a better option.

**Comment by metarsit** [comment]
I will have a work around for my private repo! Thanks @kyoungho

**Comment by kyoungho** [comment]
I will highlight the fact in the README that go get won't work without Git LFS installed. Thanks!
