### ISSUE TITLE
S3-DDS integration

### ISSUE THREAD

**Issue by giorgiozoppi** [rticommunity/rticonnextdds-connector-go#22]
### Proposal:
I would like to use this connector to allow to 
store objects received  into S3, DDS-S3 extension. I would like to know a bit more about your extension to InfluxDB. That it will be a good starting point.
Thanks,
Giorgio.

**Comment by kyoungho** [comment]
Hi @giorgiozoppi 

Sure! I did the DDS/InfluxDB integration via Telegraf. Actually, I developed a DDS input plugin (developed with Go Connector) to receive DDS data and then leveraged an output plugin for InfluxDB to ingest the DDS data to InfluxDB. As Telegraf supports parsing JSON data to its internal format, I simply converted the received DDS data to JSON and then passed it to Telegraf. Please check out the following and let me know if you have any questions. Thanks.

https://github.com/rticommunity/telegraf/tree/master/plugins/inputs/dds_consumer

**Comment by giorgiozoppi** [comment]
for the moment i will create a repository in my github

**Comment by kyoungho** [comment]
Got it. Please share your work here if you want and let me know if you run into any issues.

**Comment by giorgiozoppi** [comment]
I have tried a bit, looked around, can i refactor the binding in a go module before adding a s3 writer? At the moment looks just a couple of unordered files binded with native code.

**Comment by kyoungho** [comment]
Sure. Any improvements/contributions would be really appreciated. Please take a look at the following for contributions. 

https://github.com/rticommunity/rticonnextdds-connector-go#contributing
