### ISSUE TITLE
Add instance dispose

### ISSUE THREAD

**Issue by tom-wp** [rticommunity/rticonnextdds-connector-go#23]
### Proposal:

Add methods for disposal and unregistration of topic instances.  These actions are already supported in the connector C library, they just need a Go interface.  The dispose method could be implemented in the following form:

```
func (output *Output) Dispose() error {
	paramsCStr := C.CString(`{"action":"dispose"}`)
	defer C.free(unsafe.Pointer(paramsCStr))
	C.RTIDDSConnector_write(unsafe.Pointer(output.connector.native), output.nameCStr, paramsCStr)
	return nil
}
```

### Current behavior:

Topic instances can be written but cannot be disposed or unregistered.

### Desired behavior:

All instance actions are implemented; write, dispose and unregister.

### Use case:

A topic instance is written then later needs to be removed by the writer.

**Comment by metarsit** [comment]
If you need reviewer/tester, please let me know. We were about to write this too. But if you get to it first, please do so :)

**Comment by tom-wp** [comment]
@metarsit Thank you for the offer.   Adding the method to perform the Dispose was no issue.  I am however struggling to write a test for it.  The intention was to:

1. Output -> Write an instance.
2. Input -> Read the info state (should be Alive).
3. Output -> Dispose of the instance.
4. Input -> Read the info state (should be NotAliveDisposedInstanceState).

The issue I am having is that there is currently no method implemented on `Infos` to get the instance state.  I have tried implementing one but it appears there is no internal field named `instance_state`:

```
RTILuaSampleInfo_get:Unknown SampleInfo field: instance_state
RTILuaMetamethodImpl_InDataDereference:!RTILuaSampleInfo_get failed with retcode  1
RTILuaMetamethodImpl_InData:!dereference operation failed with retcode  1
```

Does anyone have a view into the library that can help extract this field?

**Comment by kyoungho** [comment]
Hi @tom-wp The current Connector C library does not support getting `instance_state`. It is implemented, but it is still in an internal development branch. I will update the C library once it is available.

**Comment by tom-wp** [comment]
@kyoungho, thank you.  Do you have a rough time-frame for this update?

**Comment by kyoungho** [comment]
@tom-wp The Connector C library files in the GitHub repository will be updated when our next official release is available (not sometime soon). By the time, we can provide engineering releases to you to test your code. 

An engineering release (built for x64Linux2.6gcc4.4.5) with accessing `instance_state` is already available. There is another engineering release in progress that supports accessing keyed values of disposed instances. If you like to test it with engineering releases, please contact me via email.

**Comment by tom-wp** [comment]
@kyoungho I was just trying to create self-contained test cases before submitting the pull-request.  We can test it successfully by using another participant using the standard C or Java libraries.  

What we have at the moment is working fine for us.  Thanks.

**Comment by kyoungho** [comment]
@tom-wp Thanks for your update. We can add the test code for this after the Connector C library is updated. Can you create a PR to the develop branch?

**Comment by kyoungho** [comment]
This can be done with WirteWithParams function. 
https://github.com/rticommunity/rticonnextdds-connector-go/blob/master/output.go#L59

Closing this issue.
