### ISSUE TITLE
Update connector static libraries

### ISSUE THREAD

**Issue by tom-wp** [rticommunity/rticonnextdds-connector-go#24]
### Description:

[Static libraries](https://github.com/rticommunity/rticonnextdds-connector-go/tree/master/static_lib) appear to be out of date.  They are missing the recently added functions:

```c
int RTI_Connector_get_boolean_from_infos(...);
int RTI_Connector_get_json_from_infos(...);
```

These functions were added to the header file 9 months ago whereas the static libraries are 11 months old.

### How to reproduce:

Run a static build:

```bash
$ go build -tags 'static'
```

Gives the error:

```text
# github.com/rticommunity/rticonnextdds-connector-go
/tmp/go-build901001120/b203/_x003.o: In function `_cgo_52b864e193e1_Cfunc_RTI_Connector_get_boolean_from_infos':
/tmp/go-build/cgo-gcc-prolog:406: undefined reference to `RTI_Connector_get_boolean_from_infos'
/tmp/go-build901001120/b203/_x003.o: In function `_cgo_52b864e193e1_Cfunc_RTI_Connector_get_json_from_infos':
/tmp/go-build/cgo-gcc-prolog:430: undefined reference to `RTI_Connector_get_json_from_infos'
collect2: error: ld returned 1 exit status
```

### System information:
Operating system: docker golang:1.13-stretch
Platform: x64Linux2.6gcc4.4.5 
Go version: 1.13

**Comment by kyoungho** [comment]
Thanks for reporting this. I will update the static libraries.

**Comment by tom-wp** [comment]
Great, thanks this works.  Worth noting that this now requires the 6.0.1 libraries.
