### ISSUE TITLE
USER_QOS_PROFILES.xml throws error if exists

### ISSUE THREAD

**Issue by metarsit-nutonomy** [rticommunity/rticonnextdds-connector-go#28]
### Description:
- The GO application that uses XML string fails if in the same folder contains `USER_QOS_PROFILES.xml` file
- Error return is `Invalid participant profile, xml path or xml profile`

### How to reproduce:
1. Compile a binary that takes in string XML => [writer](https://github.com/rticommunity/rticonnextdds-connector-go/blob/master/examples/xml_string/writer/writer.go)
1. Create a file with any QOS Profile in it and name it `USER_QOS_PROFILES.xml`
1. Run your binary and you should see the error

### Note
I do understand that XML string loads last but overriding it seems very funky and can be a mistake that waste people hours figuring out why. The [order of QoS Setting](https://community.rti.com/static/documentation/connext-dds/5.2.0/doc/manuals/connext_dds/html_files/RTI_ConnextDDS_CoreLibraries_UsersManual/Content/UsersManual/How_to_Load_XML_Specified_QoS_Settings.htm) is annoying. Is there a way we can bypass this? 

### System information:
Operating system: Ubuntu 18.04 (Docker)
Go version: 1.12.7

**Comment by metarsit-nutonomy** [comment]
@kyoungho I am not sure this is a known issue.

**Comment by metarsit-nutonomy** [comment]
Is there a way to do `ignore_user_profile`? Reference: [here](https://community.rti.com/static/documentation/connext-dds/5.2.0/doc/manuals/connext_dds/html_files/RTI_ConnextDDS_CoreLibraries_UsersManual/Content/UsersManual/PROFILE_QosPolicy__DDS_Extension__.htm#domains_2763211417_1237715)

**Comment by kyoungho** [comment]
@metarsit-nutonomy I will report this issue if it is not known. I think setting `ignore_user_profile` requires updating the Connector C library. 

Using QoS profiles both in code & XML files makes it complicated, and it is hard to understand which QoS settings you are using. I would like to recommend using a single method to manage your profiles if possible.

**Comment by metarsit-nutonomy** [comment]
Right, what I mean is there is a possibility that the binary that uses string XML will be in the same folder as USER Profile XML. It will be great if we can have the `ignore_user_profile` flag or something.

**Comment by kyoungho** [comment]
@metarsit-nutonomy The design intent of Connector is to simplify DDS API. Unless we have strong justification, adding capabilities is not recommended. 

I could reproduce this, and an error happens when you define duplicated profiles (e.g. domain with the same name) in USER_QOS_PROFILES.xml, which is a valid error to me.
