### ISSUE TITLE
Example Simple reader doesn't receive Square topics from the RTI DDS Ping tool

### ISSUE THREAD

**Issue by ghostravenstorm** [rticommunity/rticonnextdds-connector-go#29]
### Description:
Running the Simple example in Go trying to deconstruct how the Go connector works.
Using RTI DDS Spy and DDS Ping tools to identify how the Go examples are working.
Both the Simple reader and writer appear in the DDS Spy tool.
The DDS Ping subscriber does receive messages from the Go writer, but the Go reader doesn't receive messages from the DDS Ping publisher.

The Go reader doesn't receive messages from the RTI tools, but it does receive messages from it's companion Go writer.

### Expectation
Published messages from the DDS Ping tool should appear in the Go reader's output.

### How to reproduce:
Build the Go reader from the Simple examples and run it. Then run the RTI DDS Ping tool and publish "Square" topic "ShapeType" type messages.
Observe the Go console not receiving or outputting messages.

### System information:
Operating system: Ubuntu 20.04.1
Platform x64Linux2.6gcc4.4.5
Go version: 1.13

![image](https://user-images.githubusercontent.com/14009559/94318298-3504d180-ff56-11ea-9d55-f372a4142eb5.png)

**Comment by kyoungho** [comment]
The data type (ShapeType) used in the examples is not compatible with the data type used by DDS Ping. If you like to test the Go simple example, you can run RTI Shapes Demo (using ShapeType) and publish Square data from there.

**Comment by ghostravenstorm** [comment]
> 
> 
> The data type (ShapeType) used in the examples is not compatible with the data type used by DDS Ping. If you like to test the Go simple example, you can run RTI Shapes Demo (using ShapeType) and publish Square data from there.

Ok. What does that mean for other types being published on the DDS network?
My team is using [Fast-DDS](https://github.com/eProsima/Fast-DDS/) at our core stack and we want the Go Connector to be able to subscribe and publish to our topics defined in Fast-DDS. Our Fast-DDS implementation recieves published messages from the Go Connector, but the Go Connector doesn't work while subscribing to these topics. The Ping tool exhibits the same behaviour so I based my troubleshooting around that.

**Comment by kyoungho** [comment]
DDS topics are associated with specific data types. To establish communications between publishers and subscribers, they need to use the same topic name and compatible data types. 

You may have data types defined in IDL or XML for Fast DDS. You need to use the same data types for Go Connector to communicate with your Fast DDS applications. 

The issue you are facing may not relevant to RTI DDS Ping. I think the reason why the simple Go example does not work with DDS Ping is that they use different topics/data types.

**Comment by kyoungho** [comment]
The following XML file defines ShapeType used by the example. 
https://github.com/rticommunity/rticonnextdds-connector-go/blob/master/examples/simple/ShapeExample.xml
