### ISSUE TITLE
Git submodule is not supported by Go modules

### ISSUE THREAD

**Issue by kyoungho** [rticommunity/rticonnextdds-connector-go#3]
Currently, Connector C library is included as a Git submodule, but Git submodule is not supported when Go modules are used (which was introduced from Go 1.11).

https://github.com/golang/go/issues/24094#issuecomment-377559768

**Comment by kyoungho** [comment]
Removed the git submodule for Connector C libs and directly include them in the repository.

**Comment by metarsit** [comment]
GO seems to be pretty firm with not supporting submodule.. what about subtree?..

**Comment by kyoungho** [comment]
Yes, looks like it. I had the same issue with Dep when using submodule. I haven't tried to use subtree. Do you know it works with Go modules?

**Comment by metarsit** [comment]
Subtree should work. If you can make a branch and I can help you validate.

**Comment by kyoungho** [comment]
It would be great if it works. Do you think you can fork the repo and validate? That's how I did as well.

**Comment by metarsit** [comment]
Sure! :)

**Comment by metarsit** [comment]
@kyoungho Subtree seems to work fine. :) Feel free to close it and make Official update to your repo. https://github.com/rticommunity/rticonnextdds-connector-go/pull/5

**Comment by kyoungho** [comment]
@metarsit Great. Can you share git commands that you used to create the subtree? Thanks!

**Comment by metarsit** [comment]
It was something like `git subtree add prefix=path/to/code --squash rti master`.. along that line

**Comment by metarsit** [comment]
`git subtree add --prefix rticonnextdds-connector --squash rticonnextor master`
