### ISSUE TITLE
Increase the Code Coverage

### ISSUE THREAD

**Issue by metarsit** [rticommunity/rticonnextdds-connector-go#31]
### Proposal:
After #30, the coverage drops because I have removed many lines of redundant code. We should cover more code (>80%); this is purely line coverage.

### Current behavior:
<80%

### Desired behavior:
>80%

### Use case:
Unit tested code

**Comment by metarsit** [comment]
I cannot assign this to myself. @kyoungho can you help assign this to me?

**Comment by kyoungho** [comment]
@metarsit I just assigned it to you. Thanks!
