### ISSUE TITLE
IDL Support

### ISSUE THREAD

**Issue by metarsit** [rticommunity/rticonnextdds-connector-go#33]
### Proposal:
Currently, we only support XML file for the configuration. However, IDL is now more common used and a lot easier to manage.

### Current behavior:
Only support XML format

### Desired behavior:
Support IDL as well

### Use case:
Easy usage, supportability and readability of configuration file

**Comment by kyoungho** [comment]
@metarsit You can convert your IDL data model to XML by using rtiddsgen (rtiddsgen -convertToXml).

**Comment by metarsit** [comment]
That is an option. But it isn't always ideal to have all my IDL files converted to XML just for GO. Do you think it is possible for us to support IDL format instead?

**Comment by kyoungho** [comment]
I do not think it is possible to support IDL format directly. Connector API is based on [XML-based Application Creation](https://community.rti.com/static/documentation/connext-dds/6.0.0/doc/manuals/connext_dds/xml_application_creation/RTI_ConnextDDS_CoreLibraries_XML_AppCreation_GettingStarted.pdf) and Dynamic Data.

**Comment by metarsit** [comment]
I see. Thank you @kyoungho
