### ISSUE TITLE
Makefile with Docker

### ISSUE THREAD

**Issue by metarsit** [rticommunity/rticonnextdds-connector-go#35]
### Proposal:
Introduce makefile so we can remove local dependencies

### Current behavior:
Local

### Desired behavior:
Docker (Containerized)

**Comment by metarsit** [comment]
@kyoungho I don't have permission to do it. Can you assign to me?

**Comment by kyoungho** [comment]
I assigned to you. Thanks!

**Comment by kyoungho** [comment]
I just tested and used it. Works great. Thanks again!

**Comment by metarsit** [comment]
:) Anytime
