### ISSUE TITLE
Splitting up rticonnextdds_connector.go into specific files

### ISSUE THREAD

**Issue by metarsit** [rticommunity/rticonnextdds-connector-go#38]
### Proposal:
Split the files up to `samples.go`, `info.go`, etc

### Current behavior:
Everything is in 1 file

### Desired behavior:
Split it up a bit more so we can navigate through the function easily

### Use case:
easily navigate through the function

**Comment by kyoungho** [comment]
We can split into multiple files like C# Connector did. 
https://github.com/rticommunity/rticonnextdds-connector-cs/tree/master/src/Connector

- connector
- input
- output
- sample
- info
- instance

**Comment by metarsit** [comment]
yes exactly. We should consider doing that :) 

do you wanna pick this up or should i do it?

**Comment by kyoungho** [comment]
I will take care of this and ask you for a review. Thanks.

**Comment by metarsit** [comment]
Perfect! Thanks!

**Comment by kyoungho** [comment]
Please review the following PR. Thanks!

https://github.com/rticommunity/rticonnextdds-connector-go/pull/40

**Comment by metarsit** [comment]
Thank you. :)
