### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by mwak2** [rticommunity/rticonnextdds-connector-go#43]
### Description:
Memory usage continuously grows when reading samples.

### How to reproduce:
The example code exhibits the memory leak, but it's hard to detect it because it only processes ten samples before exiting.

I've edited the example in [my fork](https://github.com/rticommunity/rticonnextdds-connector-go/compare/develop...mwak2:feature/fix-leak-ext) to run in a tight loop so that it leaks memory faster. If you watch the reader process using a command like: `cat /proc/$(pgrep reader)/smaps | grep -i pss |  awk '{Total+=$2} END {print Total/1024" MB"}'` then you can see its memory usage continously grow.

### Proposed Fix

On [my fork](https://github.com/rticommunity/rticonnextdds-connector-go/compare/develop...mwak2:feature/fix-leak-ext), commit `4d08aa87f7d365b60e2ecc9cfd3cb38c77a52f5d` adds calls to `RTI_Connector_free_string` when receiving strings from the Connext library. These calls to `RTI_Connector_free_string` seem to have been present in `v0.3` but were removed for `v0.4`.

I'm not sure if a call to `RTI_Connector_free_string` is also requried in the `checkRetcode` function after its call to `RTI_Connector_get_last_error_message`.

### System information:
Operating system: `golang:1.15` Docker image on a Mac
Platform: x64Linux2.6gcc4.4.5 
Go version: 1.14

**Comment by kyoungho** [comment]
Sorry for getting back on this late. Can you create a PR for this? Thanks!

**Comment by treuherz** [comment]
@kyoungho My colleague that opened this issue had left the company when you replied to this issue, so I don't think he would have seen it. [His fork](https://github.com/rticommunity/rticonnextdds-connector-go/compare/develop...mwak2:feature/fix-leak-ext) linked above is still available for creating a PR, and I think you can do so without needing him to intervene. I'd take it on myself but I've never touched Cgo.

**Comment by kyoungho** [comment]
@treuherz Thanks for getting back on this! Yes, I could create a PR & merged the changes to the main branch.
