### ISSUE TITLE
Add libs for osx-arm64

### ISSUE THREAD

**Issue by tom-wp** [rticommunity/rticonnextdds-connector-go#47]
### Proposal:

Add connector libraries built for OSX (Darwin) on Arm64 in order to support M1 processors.

### Current behaviour:

The connector currently has pre-built libraries for the following platforms ([rticonnextdds-connector/lib](https://github.com/rticommunity/rticonnextdds-connector-go/tree/master/rticonnextdds-connector/lib)):

* linux-arm
* linux-arm64
* linux-x64
* osx-x64
* win-x64

### Desired behavior:

Add pre-built libraries for:

* osx-arm64

### Use case:

Running the Go Connector on Mac M1 machines.

**Comment by kyoungho** [comment]
This is not supported and it is not in our roadmap yet. If there is any change in the future, I will update here.

**Comment by tom-wp** [comment]
Thank you for clarifying.
