### ISSUE TITLE
Add dynamic build options for all architectures

### ISSUE THREAD

**Issue by tom-wp** [rticommunity/rticonnextdds-connector-go#49]
### Summary:

The dynamic cgo build file is missing options for `linux-arm` and `linux-arm64` which are now included in the connector.

### Description:

The [build_dynamic.go](https://github.com/rticommunity/rticonnextdds-connector-go/blob/master/build_dynamic.go) file only has build configuration for `linux,amd64` and `darwin`.  The [connector](https://github.com/rticommunity/rticonnextdds-connector-go/tree/master/rticonnextdds-connector/lib) now includes dynamic library files for a wide range of platforms and architectures.  The dynamic build file should be extended to match the connector build list:

- linux-arm
- linux-arm64
- linux-x64
- osx-x64
- win-x64

For example, for `linux-arm64`, the following lines need to be added (please check):

```
// #cgo linux,arm64 CFLAGS: -I${SRCDIR}/include -I${SRCDIR}/rticonnextdds-connector/include -DRTI_UNIX -DRTI_LINUX -DRTI_64BIT
// #cgo linux,arm64 LDFLAGS: -L${SRCDIR}/rticonnextdds-connector/lib/linux-arm64 -lrtiddsconnector -ldl -lnsl -lm -lpthread -lrt -Wl,-rpath,${SRCDIR}/rticonnextdds-connector/lib/linux-arm64

```

### System information:
Operating system:
Platform (e.g. linux arm64): 
Go version: 1.19

**Comment by kyoungho** [comment]
Will add them once I complete testing on these platforms

**Comment by mbruggs** [comment]
Hello, I was wondering if there has been any update on these additional architectures? Having linux/arm64 would be useful for me too.

**Comment by kyoungho** [comment]
Added the build flags for arm64. Please reopen if you have any issues.
