### ISSUE TITLE
Possible memory leak on DDS exception

### ISSUE THREAD

**Issue by tom-wp** [rticommunity/rticonnextdds-connector-go#50]
Does the line below cause a c-layer memory leak as the method `RTI_Connector_get_last_error_message()` appears to return a pointer to memory assigned by the connector?  There is no corresponding free after creating the Go string.

https://github.com/rticommunity/rticonnextdds-connector-go/blob/efab2f041046b9fe3a78090e9647e5beed7a301f/rticonnextdds_connector.go#L210

**Comment by tom-wp** [comment]
Actually, this line is confusing as `RTI_Connector_get_last_error_message` is defined as a function but seems to be used as a variable.  Maybe this is a subtly of CGo I'm not aware of.

**Comment by kyoungho** [comment]
As it does not allocate memory in the c layer, I think it would not cause memory leak. However, there is a mistake in the statement (should be a function not a variable). I will fix it. Thanks.
