### ISSUE TITLE
Remove static libraries from project

### ISSUE THREAD

**Issue by tom-wp** [rticommunity/rticonnextdds-connector-go#54]
### Proposal:

The project contains both static and dynamic libraries.  My understanding is that the static libraries are no longer maintained (https://github.com/rticommunity/rticonnextdds-connector-go/issues/48) and the dynamic libraries should always be used.   Suggestion is to remove the static libraries from the project for two reasons:

1. Using outdated static libraries causes problems with incompatibility of function signatures
2. Having the static libraries in the project requires `git-lfs` which causes a number of problems with Go projects

**Comment by kyoungho** [comment]
@tom-wp I just removed the static libs from the repository. Please reopen this issue by leaving a comment here if you still have any issues/requests. Thanks.

**Comment by kyoungho** [comment]
@tom-wp I created v0.5.4 tag with the static libs removed.

**Comment by tom-wp** [comment]
Thank you.
