### ISSUE TITLE
SIGSEGEV: Segmentation violation 

### ISSUE THREAD

**Issue by LiorGandin** [rticommunity/rticonnextdds-connector-go#56]
### Description:
When running multiple go routines, different types of errors start to pop up. Most prominently, SIGSEGEV: Segmentation violation, but they vary. I have tried to counter it with Mutex and had some success, but it still pops up. I am using the ShapeExample.xml you provided in your README just changed the names from "MySquareReader" to "MyReader" and the same goes for the writer. I have noticed that this error is much more prevalent with the reader than with the writer.
Sorry for the formatting. 

### How to reproduce:
**rti.go:**
`
package main

import (
	"encoding/json"
	"log"
	"strconv"
	"sync"
	"time"

	rtiGo "github.com/rticommunity/rticonnextdds-connector-go"
)

// RTIModule is the main structure for the RTI module.
type RTIModule struct {
	connector  *rtiGo.Connector
	muWriters  sync.Mutex
	muReaders  sync.Mutex
	numWriters int
	numReaders int
}

// Init initializes the RTI module.
func (r *RTIModule) Init(configFilePath, configName string, numGoroutinesWriters int, numGoroutinesReaders int) {
	var err error
	r.connector, err = rtiGo.NewConnector(configName, configFilePath)

	r.numWriters = numGoroutinesWriters
	r.numReaders = numGoroutinesReaders

	if err != nil {
		log.Fatalf("Failed to create RTI Connector: %v", err)
	}
}

// GetRealTimeData is an example function that retrieves real-time data.
func (r *RTIModule) GetRealTimeData(id int) string {
	log.Printf("Goroutine %d is trying to acquire the lock\n", id)
	r.muReaders.Lock()
	log.Printf("Goroutine %d has acquired the lock\n", id)
	defer func() {
		log.Printf("Goroutine %d is releasing the lock\n", id)
		r.muReaders.Unlock()
	}()
	if r.connector == nil {
		return "RTI Connector not initialized"
	}

	input, _ := r.connector.GetInput("MySubscriber::MyReader")
	if input == nil {
		return "Failed to get input"
	}
	r.connector.Wait(3000)
	input.Take()
	numOfSamples, _ := input.Samples.GetLength()
	for i := 0; i < numOfSamples; i++ {
		valid, _ := input.Infos.IsValid(i)
		if valid {
			data, err := input.Samples.GetJSON(i)
			if err != nil {
				return err.Error()
			} else {
				return string(data)
			}
		}
	}
	return "No data available"
}

// GetRealTimeFracturedData is an example function that retrieves real-time data.
func (r *RTIModule) GetRealTimeFracturedData(messageLength int, isDurableOrReliable bool, id int) []byte {
	log.Printf("Goroutine %d is trying to acquire the READRER lock\n", id)
	r.muReaders.Lock()
	log.Printf("Goroutine %d has acquired the READRER lock\n", id)
	defer func() {
		log.Printf("Goroutine %d is releasing the READRER lock\n", id)
		r.muReaders.Unlock()
	}()
	if r.connector == nil {
		return []byte("RTI Connector not initialized")
	}

	input, _ := r.connector.GetInput("MySubscriber::MyReader")
	if input == nil {
		return []byte("Failed to get input")
	}
	bytesRecieved := 0
	var data []byte
	var receivedByte byte
	var err error
	r.connector.Wait(3000)
	input.Take()
	numOfSamples, _ := input.Samples.GetLength()
	for i := 0; i < numOfSamples; i++ {
		valid, _ := input.Infos.IsValid(i)
		if valid {
			if isDurableOrReliable {
				receivedByte, err = input.Samples.GetByte(bytesRecieved, "b")
			} else {
				receivedByte, err = input.Samples.GetByte(0, "b")
			}
			bytesRecieved++
			if err != nil {
				return []byte(err.Error())
			}
			data = append(data, []byte{receivedByte}...)
		}
		if bytesRecieved == messageLength {
			return data
		}
	}
	log.Printf("Goroutine %d unfinished data %s\n", id, string(data))
	return []byte("Was unable to get data in it's entirety")
}

// WriteRealTimeData writes data to the DataWriter.
func (r *RTIModule) WriteRealTimeData(jsonData string, id int) string {
	log.Printf("Goroutine %d is trying to acquire the lock\n", id)
	r.muWriters.Lock()
	log.Printf("Goroutine %d has acquired the lock\n", id)
	defer func() {
		log.Printf("Goroutine %d is releasing the lock\n", id)
		r.muWriters.Unlock()
	}()
	if r.connector == nil {
		return "RTI Connector not initialized"
	}

	output, _ := r.connector.GetOutput("MyPublisher::MyWriter")
	if output == nil {
		return "Failed to get output"
	}

	var result map[string]interface{}
	marshalErr := json.Unmarshal([]byte(jsonData), &result)
	if marshalErr != nil {
		return "Failed to UnMarshal data: " + marshalErr.Error()
	}
	data, _ := json.Marshal(result)

	output.Instance.SetJSON(data)
	err := output.Write()
	if err != nil {
		return "Failed to write data: " + err.Error()
	}
	byteCount := len(data)
	return strconv.Itoa(byteCount)
}

// WriteRealTimeDataByRate writes data to the DataWriter by rate.
func (r *RTIModule) WriteRealTimeDataByRate(jsonData string, rate int, size int, id int) string {
	log.Printf("Goroutine %d is trying to acquire the lock\n", id)
	r.muWriters.Lock()
	log.Printf("Goroutine %d has acquired the lock\n", id)
	defer func() {
		log.Printf("Goroutine %d is releasing the lock\n", id)
		r.muWriters.Unlock()
	}()
	if r.connector == nil {
		return "RTI Connector not initialized"
	}

	output, _ := r.connector.GetOutput("MyPublisher::MyWriter")
	if output == nil {
		return "Failed to get output"
	}

	var result map[string]interface{}
	marshalErr := json.Unmarshal([]byte(jsonData), &result)
	if marshalErr != nil {
		return "Failed to UnMarshal data: " + marshalErr.Error()
	}
	data, _ := json.Marshal(result)

	for i := 0; i < len(data); i += size * rate {
		for j := 0; j < size; j++ {
			if i+j > len(data) {
				return "All Data Has Been Written Successfully"
			}
			output.Instance.SetByte("b", data[i+j])
			err := output.Write()
			if err != nil {
				return "Failed to write data: " + err.Error()
			}
			time.Sleep(time.Duration(rate/size) * time.Second)
		}
	}
	return "All Data Has Been Written Successfully"
}

func NewRTIModule() *RTIModule {
	return &RTIModule{}
}

func main() {
	r := NewRTIModule()
	r.Init("/home/gandin/ShapeExample.xml", "MyParticipantLibrary::Zero", 1, 1)

	var wg sync.WaitGroup
	wg.Add(120)

	for i := 1; i <= 120; i++ {
		go func(id int) {
			defer wg.Done()
			log.Printf("GoRoutine number %d: Size of data: %s\n", i, r.WriteRealTimeData(`{ "b": 123 }`, i))
		}(i)
		go func(id int) {
			defer wg.Done()
			log.Printf("GoRoutine number %d: Received data: %s\n", i, r.GetRealTimeData(i))
		}(i)
	}

	wg.Wait()
	log.Println("All goroutines have finished executing")
}
`

**To run just write "go run rti.go"**

### System information:
Operating system:
Linux 6.8.0-35-generic
Go version:
go1.22.2 linux/amd64

**Comment by kyoungho** [comment]
@LiorGandin As stated in the following link, operations on the same Connector instance are not protected for multi-threaded access. 

https://community.rti.com/static/documentation/connector/1.0.0/api/python/threading.html#threading-model

Thanks for providing the reproducible code. I could reproduce the issue. After I create a separate Connector instance for reader and writer, the error did not occur to me. Or I think using the same lock for reader/writer (lock per connector) could be another way to resolve it (I have not tried this).
