### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by kyoungho** [rticommunity/rticonnextdds-connector-go#8]
### Description:
```
$ go get github.com/rticommunity/rticonnextdds-connector-go

# github.com/rticommunity/rticonnextdds-connector-go /usr/bin/ld:/home/kyoungho/go/src/github.com/rticommunity/rticonnextdds-connector-go/rticonnextdds-connector/lib/x64Linux2.6gcc4.4.5/librtiddsconnector.so: file format not recognized; treating as linker script 
/usr/bin/ld:/home/kyoungho/go/src/github.com/rticommunity/rticonnextdds-connector-go/rticonnextdds-connector/lib/x64Linux2.6gcc4.4.5/librtiddsconnector.so:1: syntax error collect2: error: ld returned 1 exit status
```
### How to reproduce:
go get github.com/rticommunity/rticonnextdds-connector-go

### System information:
Operating system: Ubuntu 16.04
Platform (e.g. x64Linux2.6gcc4.4.5): x64Linux2.6gcc4.4.5
Go version: 1.12.6

**Comment by kyoungho** [comment]
The issue happens when a Git LFS extension is not installed on your machine. We use Git LFS for our C library files as they are large binary files. If Git LFS is not installed, it won't properly check out the library files. go get does not give you any warnings and print the linking error messages. 

If you use Ubuntu 16.04. Please use the following commands to install Git LFS. 
```
$ curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash 
$ sudo apt-get install git-lfs
```

**Comment by paperclip4465** [comment]
I am also having this issue on Ubuntu 18.04 and i have git lfs installed

**Comment by kyoungho** [comment]
Did you check out the repo before installing Git LFS? If so, can you try to remove it and check out again? If you checked out with `$ go get ...`, it would be located at `~/go/src/github/rticommunity/rticonnextdds-connector-go`.

**Comment by paperclip4465** [comment]
The issue seemed to be the fact that my project was located outside my $GOPATH. moving the project to $GOPATH/src/ seems to have fixed it.

This may not be the appropriate place to ask, but when i try to cross compile for arm it tells me i can't build this project. Is this intentional or is there something special i need to do.

**Comment by metarsit-nutonomy** [comment]
Usually I encounter this problem because `go get` only download .go files which means the important stuff aren't coming along with it.. :(

**Comment by kyoungho** [comment]
@metarsit-nutonomy Do you encounter this issue even after installing Git LFS? On my side, `go get` downloads both go files & C library files.

**Comment by metarsit-nutonomy** [comment]
Yap. I have git-lfs on my machine.

maybe i might have misconfigure stuff 🤔

**Comment by kyoungho** [comment]
@paperclip4465 cross compilation is possible, but you need to install the cross compiler for a target architecture. This it what I did on a Ubuntu machine to cross compile for arm:

`$ apt-get install gcc-arm-linux-gnueabihf`
`$ export CC=arm-linux-gnueabihf-gcc
`$ GOOS=linux GOARCH=arm GOARM=6 CGO_ENABLED=1 go build -v -o  -ldflags="-extld=$CC"` 

I copied a generated executable, the Connector C library file for arm, and an XML configuration file to a raspberry pi and it worked.
